-- Temporal Preview

local temporalPreviewShips = mods.multiverse.temporalPreviewShips
temporalPreviewShips["PLAYER_SHIP_FR_METAL_LANIUS"] = true
temporalPreviewShips["PLAYER_SHIP_FR_METAL_LANIUS_2"] = true
temporalPreviewShips["PLAYER_SHIP_FR_METAL_LANIUS_3"] = true
temporalPreviewShips["PLAYER_SHIP_FR_METAL_DIAMOND"] = true
temporalPreviewShips["PLAYER_SHIP_FR_METAL_DIAMOND_2"] = true
temporalPreviewShips["PLAYER_SHIP_FR_METAL_DIAMOND_3"] = true
temporalPreviewShips["PLAYER_SHIP_FR_OPERATOR"] = true
temporalPreviewShips["PLAYER_SHIP_FR_OPERATOR_2"] = true
temporalPreviewShips["PLAYER_SHIP_FR_OPERATOR_3"] = true
temporalPreviewShips["PLAYER_SHIP_FR_ALLOY"] = true
temporalPreviewShips["PLAYER_SHIP_FR_ALLOY_2"] = true
temporalPreviewShips["PLAYER_SHIP_FR_ALLOY_3"] = true

local roomEffectShips = mods.fusion.roomEffectShips
roomEffectShips.PLAYER_SHIP_FR_METAL_LANIUS = true
roomEffectShips.PLAYER_SHIP_FR_METAL_LANIUS_2 = true
roomEffectShips.PLAYER_SHIP_FR_METAL_LANIUS_3 = true
roomEffectShips.PLAYER_SHIP_FR_METAL_DIAMOND = true
roomEffectShips.PLAYER_SHIP_FR_METAL_DIAMOND_2 = true
roomEffectShips.PLAYER_SHIP_FR_METAL_DIAMOND_3 = true
roomEffectShips.PLAYER_SHIP_FR_OPERATOR = true
roomEffectShips.PLAYER_SHIP_FR_OPERATOR_2 = true
roomEffectShips.PLAYER_SHIP_FR_OPERATOR_3 = true
roomEffectShips.PLAYER_SHIP_FR_ALLOY = true
roomEffectShips.PLAYER_SHIP_FR_ALLOY_2 = true
roomEffectShips.PLAYER_SHIP_FR_ALLOY_3 = true

